name: Atualizar HTML manualmente

on:
  workflow_dispatch:  # permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium beautifulsoup4

      - name: Executar script Python
        run: python main.py

      - name: Commit do novo HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Atualização manual do HTML"
          git push
